jobs:
# Mac and Linux use the same template with different matrixes
- template: buildscripts/azure/azure-linux-macos.yml
  parameters:
    name: macOS
    vmImage: macos-11
    matrix:
      py39:
        PYTHON: '3.9'
        CONDA_ENV: cienv
        LLVM: '17'
      py310:
        PYTHON: '3.10'
        CONDA_ENV: cienv
        LLVM: '17'
      py311:
        PYTHON: '3.11'
        CONDA_ENV: cienv
        LLVM: '17'
      py312:
        PYTHON: '3.12'
        CONDA_ENV: cienv
        LLVM: '17'

- template: buildscripts/azure/azure-linux-macos.yml
  parameters:
    name: Linux
    vmImage: ubuntu-20.04
    matrix:
      py39:
        PYTHON: '3.9'
        CONDA_ENV: cienv
        RUN_FLAKE8: yes
        LLVM: '17'
      py310:
        PYTHON: '3.10'
        CONDA_ENV: cienv
        RUN_FLAKE8: yes
        LLVM: '17'
      py311:
        PYTHON: '3.11'
        CONDA_ENV: cienv
        RUN_FLAKE8: yes
        RUN_CLANG_FORMAT: yes
        LLVM: '17'
      py312:
        PYTHON: '3.12'
        CONDA_ENV: cienv
        RUN_FLAKE8: yes
        RUN_CLANG_FORMAT: yes
        LLVM: '17'
# temporarily disabled
#       pypy:
#         PYTHON: pypy
#         CONDA_ENV: cienv
      py39_wheel:
        PYTHON: '3.9'
        CONDA_ENV: cienv
        WHEEL: 'yes'
        LLVM: '17'
      py310_wheel:
        PYTHON: '3.10'
        CONDA_ENV: cienv
        WHEEL: 'yes'
        LLVM: '17'
      py311_wheel:
        PYTHON: '3.11'
        CONDA_ENV: cienv
        WHEEL: 'yes'
        LLVM: '17'
      py312_wheel:
        PYTHON: '3.12'
        CONDA_ENV: cienv
        WHEEL: 'yes'
        LLVM: '17'

      py39_docs:
        PYTHON: '3.9'
        CONDA_ENV: cienv
        BUILD_DOCS: 'yes'

- template: buildscripts/azure/azure-windows.yml
  parameters:
    name: Windows
    vmImage: windows-2019

- job: check_formatting
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      set -e
      sudo apt install -y clang-format
      clang-format -n -Werror ffi/*.cpp ffi/*.h
    displayName: Check C++ formatting
